version: '3'

services:
  mediathekview:
    build: .
    container_name: mediathekview
    ports:
      - "5800:5800"
    volumes:
      - "/did/mediathek:/config:rw"
      - "/mnt/hdds/media/mediathek:/output:rw"
    environment:
       - "USER_ID=568"
       - "GROUP_ID=568"
